<?php
/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$mediaUrl = $this->getViewFileUrl('images');
?>
<style type="text/css">
.page-header .header-content .block-search .action.search::before{content: "" !important;background: url(<?php echo $mediaUrl; ?>/search.png);width:22px;height:22px;background-repeat: no-repeat;cursor: pointer;background-size: 22px;}
.account-nav .header.panel::before{content: "" !important;background: url(<?php echo $mediaUrl; ?>/user.png);width:22px;height:26px;background-repeat: no-repeat;cursor: pointer;background-size: 19px;}
.page-header .header-content .minicart-wrapper .action.showcart::before{content: '';background: url(<?php echo $mediaUrl; ?>/cart.png);width: 28px;height: 18px;background-repeat: no-repeat;background-size: cover;}
.page-header .header-content .block-search .block-content form .field.search .label:before { content: ""; background: url(<?php echo $mediaUrl; ?>/search.png); background-repeat: no-repeat; cursor: pointer; width: 22px; height: 22px; background-size: 22px; }
</style>