<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<div class="container">
    <div class="product-note-footer-container">
        <div class="product-note-footer-box">
            <span class="product-note-footer-title">a note from the editor</span>
            <p class="product-note-footer-description">The Forte Lurex Linen Viscose Jacket in Mother of Pearl features lunar lavishness by night and by day: a blazer in a linen blend shot with lurex for a shimmering surface that shines like a star in the sky.</p>
            <div class="product-note-footer-auther">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="28" height="2">
                    <path d="M0 0 C9.24 0 18.48 0 28 0 C28 0.66 28 1.32 28 2 C18.76 2 9.52 2 0 2 C0 1.34 0 0.68 0 0 Z " fill="#000000" transform="translate(0,0)"/>
                </svg>
                <span class="auther-name"> By <span>MINNA SHIM</span>, Fashion Editor </span>
            </div>
        </div>
    </div>
</div>